export type TokenType =
  // Single-character tokens.
  | "LEFT_PAREN"
  | "RIGHT_PAREN"
  | "LEFT_BRACE"
  | "RIGHT_BRACE"
  | "COMMA"
  | "DOT"
  | "MINUS"
  | "PLUS"
  | "SEMICOLON"
  | "SLASH"
  | "STAR"
  | "COLON"
  | "MODULUS"
  // One or two character tokens.
  | "BANG"
  | "BANG_EQUAL"
  | "EQUAL"
  | "EQUAL_EQUAL"
  | "GREATER"
  | "GREATER_EQUAL"
  | "LESS"
  | "LESS_EQUAL"
  // Literals.
  | "IDENTIFIER"
  | "STRING"
  | "NUMBER"
  // Keywords.
  | "AND"
  // | "CLASS"
  | "ELSE"
  | "FALSE"
  | "FUNCTION"
  // | "FOR"
  | "IF"
  | "NIL"
  | "OR"
  // | "PRINT"
  | "RETURN"
  // | "SUPER"
  // | "THIS"
  | "TRUE"
  | "VARIABLE"
  | "WHILE"
  | "BREAK"
  | "CONTINUE"
  // types
  | "INTEGER"
  | "FLOAT"
  | "BOOLEAN"
  | "STRING"
  // End of File
  | "EOF";
